version: "3"

services:
  
  rabbit:
    image: rabbitmq:3-management
    hostname: rabbit
    volumes:
      - "./rabbitmq.config:/etc/rabbitmq/rabbitmq.config"
      - "./definitions.json:/etc/rabbitmq/definitions.json"
    ports:
      - "5672:5672"
      - "15672:15672"