spring:
  application:
    name: @name@
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: @activatedProperties@
  rabbitmq:
    host: @rabbitmq.host@
    port: @rabbitmq.port@
    username: @rabbitmq.username@
    password: @rabbitmq.password@
server:
  port: @server.port@
  servlet:
    context-path: /
logging:
  level:
    root: @log.level@